name: Hoyo auto check-in

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC, which is 8 AM GMT+8
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run auto check-in script
        env:
          COOKIE: ${{ secrets.COOKIE }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: python autocheckin.py
